version: 0.2

env:
  variables:
    DOMAIN: "ecommerce-domain"
    REPO: "ecommerce-shared"
    REGION: "ap-southeast-1"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "[INSTALL] Running aws sts get-caller-identity..."
      - aws sts get-caller-identity

      - echo "[INSTALL] Extracting AWS Account ID..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo "[INSTALL] Exporting CodeArtifact auth token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $DOMAIN --domain-owner $AWS_ACCOUNT_ID --region $REGION --query authorizationToken --output text)
      - echo "[DEBUG] CODEARTIFACT_AUTH_TOKEN first 10 chars:" $(echo $CODEARTIFACT_AUTH_TOKEN | cut -c1-10)
      - echo "[INSTALL] Running aws codeartifact get-authorization-token..."
      - aws codeartifact get-authorization-token --domain $DOMAIN --domain-owner $AWS_ACCOUNT_ID --region $REGION



      - echo "[INSTALL] Generating Maven settings.xml for CodeArtifact..."
      - mkdir -p ~/.m2
      - |
        cat > ~/.m2/settings.xml <<EOL
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
          <mirrors>
            <mirror>
              <id>codeartifact</id>
              <mirrorOf>*</mirrorOf>
              <url>https://${DOMAIN}-${AWS_ACCOUNT_ID}.d.codeartifact.${REGION}.amazonaws.com/maven/${REPO}/</url>
            </mirror>
          </mirrors>
          <servers>
            <server>
              <id>codeartifact</id>
              <username>aws</username>
              <password>${CODEARTIFACT_AUTH_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOL

  build:
    commands:
      - echo "[BUILD] Starting Maven build..."
      - mvn clean install -s ~/.m2/settings.xml -DskipTests -U
      - mvn deploy -s ~/.m2/settings.xml -DskipTests

artifacts:
  files:
    - '**/pom.xml'
